"""Generate wii/hot_layout.h from wii/hot_layout.txt (functions hottest first,
from a physical-Wii PC profile). With VIPER_WII_HOT_LAYOUT each listed
function is placed in section .text.sorted.NNNN by rank; libogc's linker
script sorts those by name ahead of the rest of .text, so the hot code is
contiguous in hottest-first order. Placement only: no instruction changes.
Generated guest functions are redeclared here (the generated-code pass
includes this header); hand-written functions use WII_HOT_<name>.
Run: python3 wii/gen_hot_layout.py"""
from pathlib import Path
import re

root = Path(__file__).resolve().parent
names = [l.strip() for l in (root / 'hot_layout.txt').read_text().splitlines()
         if l.strip() and not l.startswith('#')]
macros, protos = [], []
for i, name in enumerate(names):
    rank = f'"{i + 1:04d}"'
    base = re.sub(r'\.(lto_priv|isra|constprop|part)\..*$', '', name)
    if re.fullmatch(r'f_[a-z]+_[0-9a-f]+', base):
        protos.append(f'void {base}(PPCContext *c) WII_HOT_ATTR({rank});')
    elif re.fullmatch(r'[A-Za-z_]\w*', base):
        macros.append(f'#define WII_HOT_{base} WII_HOT_ATTR({rank})')
out = ['/* Generated by wii/gen_hot_layout.py from wii/hot_layout.txt: do not edit. */',
       '#ifndef WII_HOT_LAYOUT_H', '#define WII_HOT_LAYOUT_H',
       '#ifdef VIPER_WII_HOT_LAYOUT',
       '#define WII_HOT_ATTR(rank) __attribute__((section(".text.sorted." rank)))',
       '#else', '#define WII_HOT_ATTR(rank)', '#endif'] + macros + ['#endif',
       '/* Guest functions: only where PPCContext is known (wii/native_ram.h). */',
       '#if defined(WII_HOT_GUEST_PROTOTYPES) && !defined(WII_HOT_GUEST_DONE)',
       '#define WII_HOT_GUEST_DONE'] + protos + ['#endif']
text = '\n'.join(out) + '\n'
(root / 'hot_layout.h').write_text(text)
print(f'{len(names)} hot functions -> wii/hot_layout.h')
