/* Generated by wii/gen_hot_layout.py from wii/hot_layout.txt: do not edit. */
#ifndef WII_HOT_LAYOUT_H
#define WII_HOT_LAYOUT_H
#ifdef VIPER_WII_HOT_LAYOUT
#define WII_HOT_ATTR(rank) __attribute__((section(".text.sorted." rank)))
#else
#define WII_HOT_ATTR(rank)
#endif
#define WII_HOT_wii_native_gl_0002adac WII_HOT_ATTR("0001")
#define WII_HOT_triangle WII_HOT_ATTR("0002")
#define WII_HOT_wii_voodoo_direct_triangles WII_HOT_ATTR("0004")
#define WII_HOT_triangle_full WII_HOT_ATTR("0005")
#define WII_HOT_wii_rsqrt_exact WII_HOT_ATTR("0007")
#define WII_HOT_triangle_packet WII_HOT_ATTR("0008")
#define WII_HOT_gx_batch_flush WII_HOT_ATTR("0011")
#define WII_HOT_fifo_run_loop WII_HOT_ATTR("0012")
#define WII_HOT_bind_flat_texture WII_HOT_ATTR("0014")
#define WII_HOT_voodoo_lfb_write WII_HOT_ATTR("0015")
#define WII_HOT_voodoo_reg_write WII_HOT_ATTR("0016")
#define WII_HOT_wii_native_gl_00029d28 WII_HOT_ATTR("0018")
#define WII_HOT_memcpy WII_HOT_ATTR("0019")
#define WII_HOT_wii_gx_color_equation_at WII_HOT_ATTR("0020")
#define WII_HOT_rt_call WII_HOT_ATTR("0021")
#define WII_HOT_wii_gx_tmu_pipeline_plan WII_HOT_ATTR("0023")
#define WII_HOT_wii_gx_tmu_state_le WII_HOT_ATTR("0031")
#define WII_HOT_wii_gx_pipeline_plan WII_HOT_ATTR("0034")
#define WII_HOT_fifo_describe WII_HOT_ATTR("0038")
#define WII_HOT_memset WII_HOT_ATTR("0040")
#define WII_HOT_wii_voodoo_bulk_writer_be WII_HOT_ATTR("0044")
#define WII_HOT___GX_SetDirtyState WII_HOT_ATTR("0051")
#define WII_HOT_gx_batch_reserve WII_HOT_ATTR("0052")
#define WII_HOT_fifo_consume WII_HOT_ATTR("0053")
#define WII_HOT_rt_mftb WII_HOT_ATTR("0054")
#define WII_HOT_rt_mmio_w32 WII_HOT_ATTR("0056")
#define WII_HOT_wii_voodoo_bulk_tail_ready WII_HOT_ATTR("0057")
#define WII_HOT_GX_InitTexObjLOD WII_HOT_ATTR("0061")
#define WII_HOT_wii_gx_rejection WII_HOT_ATTR("0064")
#define WII_HOT_lz_texcoordgen WII_HOT_ATTR("0068")
#define WII_HOT_gx_lazy_send WII_HOT_ATTR("0093")
#define WII_HOT_hw_read_ WII_HOT_ATTR("0098")
#define WII_HOT_memcmp WII_HOT_ATTR("0100")
#define WII_HOT_clip WII_HOT_ATTR("0101")
#define WII_HOT_GX_SetTevKAlphaSel WII_HOT_ATTR("0103")
#define WII_HOT_projection WII_HOT_ATTR("0121")
#define WII_HOT___GXDefTexRegionCallback WII_HOT_ATTR("0123")
#define WII_HOT_GX_InitTexObj WII_HOT_ATTR("0129")
#define WII_HOT___fixunsdfdi WII_HOT_ATTR("0140")
#define WII_HOT_GX_SetTevOrder WII_HOT_ATTR("0147")
#define WII_HOT_GX_SetTevColorOp WII_HOT_ATTR("0154")
#define WII_HOT_rt_mmio_r16 WII_HOT_ATTR("0165")
#define WII_HOT_wii_rejection_policy WII_HOT_ATTR("0176")
#define WII_HOT_GX_Begin WII_HOT_ATTR("0178")
#define WII_HOT_rt_check WII_HOT_ATTR("0179")
#endif
/* Guest functions: only where PPCContext is known (wii/native_ram.h). */
#if defined(WII_HOT_GUEST_PROTOTYPES) && !defined(WII_HOT_GUEST_DONE)
#define WII_HOT_GUEST_DONE
void f_gl_00028fc4(PPCContext *c) WII_HOT_ATTR("0003");
void f_gl_000210a8(PPCContext *c) WII_HOT_ATTR("0006");
void f_gl_00021ed0(PPCContext *c) WII_HOT_ATTR("0009");
void f_gl_000281ac(PPCContext *c) WII_HOT_ATTR("0010");
void f_gl_00021940(PPCContext *c) WII_HOT_ATTR("0013");
void f_k_00012648(PPCContext *c) WII_HOT_ATTR("0017");
void f_g_0003f6dc(PPCContext *c) WII_HOT_ATTR("0022");
void f_g_000b9844(PPCContext *c) WII_HOT_ATTR("0024");
void f_g_00042aa4(PPCContext *c) WII_HOT_ATTR("0025");
void f_g_000b9784(PPCContext *c) WII_HOT_ATTR("0026");
void f_gl_000248b0(PPCContext *c) WII_HOT_ATTR("0027");
void f_gl_000201e8(PPCContext *c) WII_HOT_ATTR("0028");
void f_g_0004b4b4(PPCContext *c) WII_HOT_ATTR("0029");
void f_s_009a8058(PPCContext *c) WII_HOT_ATTR("0030");
void f_s_009a73b0(PPCContext *c) WII_HOT_ATTR("0032");
void f_g_00064be4(PPCContext *c) WII_HOT_ATTR("0033");
void f_s_009a4030(PPCContext *c) WII_HOT_ATTR("0035");
void f_g_0007da9c(PPCContext *c) WII_HOT_ATTR("0036");
void f_gl_00024d28(PPCContext *c) WII_HOT_ATTR("0037");
void f_g_00041d2c(PPCContext *c) WII_HOT_ATTR("0039");
void f_g_0003fea4(PPCContext *c) WII_HOT_ATTR("0041");
void f_g_00038098(PPCContext *c) WII_HOT_ATTR("0042");
void f_k_00012570(PPCContext *c) WII_HOT_ATTR("0043");
void f_gl_0002a004(PPCContext *c) WII_HOT_ATTR("0045");
void f_s_009a09cc(PPCContext *c) WII_HOT_ATTR("0046");
void f_gl_000211d4(PPCContext *c) WII_HOT_ATTR("0047");
void f_gl_00022340(PPCContext *c) WII_HOT_ATTR("0048");
void f_gl_00022e18(PPCContext *c) WII_HOT_ATTR("0049");
void f_gl_0002132c(PPCContext *c) WII_HOT_ATTR("0050");
void f_gl_00022314(PPCContext *c) WII_HOT_ATTR("0055");
void f_g_0004b930(PPCContext *c) WII_HOT_ATTR("0058");
void f_k_000125c0(PPCContext *c) WII_HOT_ATTR("0059");
void f_g_000ac534(PPCContext *c) WII_HOT_ATTR("0060");
void f_s_009a13e4(PPCContext *c) WII_HOT_ATTR("0062");
void f_g_000435f0(PPCContext *c) WII_HOT_ATTR("0063");
void f_gl_00024c90(PPCContext *c) WII_HOT_ATTR("0065");
void f_g_000b938c(PPCContext *c) WII_HOT_ATTR("0066");
void f_g_0005bf3c(PPCContext *c) WII_HOT_ATTR("0067");
void f_g_0003f5f4(PPCContext *c) WII_HOT_ATTR("0069");
void f_g_00045dd8(PPCContext *c) WII_HOT_ATTR("0070");
void f_s_009a7180(PPCContext *c) WII_HOT_ATTR("0071");
void f_g_0003dfc4(PPCContext *c) WII_HOT_ATTR("0072");
void f_g_00066cb4(PPCContext *c) WII_HOT_ATTR("0073");
void f_g_0003b4ac(PPCContext *c) WII_HOT_ATTR("0074");
void f_g_0007deac(PPCContext *c) WII_HOT_ATTR("0075");
void f_k_0000f0a0(PPCContext *c) WII_HOT_ATTR("0076");
void f_s_009a0c20(PPCContext *c) WII_HOT_ATTR("0077");
void f_gl_00029b28(PPCContext *c) WII_HOT_ATTR("0078");
void f_g_0003f51c(PPCContext *c) WII_HOT_ATTR("0079");
void f_g_000804e0(PPCContext *c) WII_HOT_ATTR("0080");
void f_g_000419d0(PPCContext *c) WII_HOT_ATTR("0081");
void f_g_00042c30(PPCContext *c) WII_HOT_ATTR("0082");
void f_g_000567d4(PPCContext *c) WII_HOT_ATTR("0083");
void f_gl_00021b9c(PPCContext *c) WII_HOT_ATTR("0084");
void f_g_000428f4(PPCContext *c) WII_HOT_ATTR("0085");
void f_g_000415c0(PPCContext *c) WII_HOT_ATTR("0086");
void f_k_0000a1e4(PPCContext *c) WII_HOT_ATTR("0087");
void f_g_00043618(PPCContext *c) WII_HOT_ATTR("0088");
void f_gl_00027668(PPCContext *c) WII_HOT_ATTR("0089");
void f_g_0007e2d0(PPCContext *c) WII_HOT_ATTR("0090");
void f_g_0009f6b8(PPCContext *c) WII_HOT_ATTR("0091");
void f_g_0007fc40(PPCContext *c) WII_HOT_ATTR("0092");
void f_g_000b1da4(PPCContext *c) WII_HOT_ATTR("0094");
void f_gl_00024930(PPCContext *c) WII_HOT_ATTR("0095");
void f_g_0003f1f4(PPCContext *c) WII_HOT_ATTR("0096");
void f_g_0008f828(PPCContext *c) WII_HOT_ATTR("0097");
void f_g_0003e298(PPCContext *c) WII_HOT_ATTR("0099");
void f_k_000102ec(PPCContext *c) WII_HOT_ATTR("0102");
void f_k_00000500(PPCContext *c) WII_HOT_ATTR("0104");
void f_g_0003f17c(PPCContext *c) WII_HOT_ATTR("0105");
void f_k_0000a11c(PPCContext *c) WII_HOT_ATTR("0106");
void f_g_0005cf74(PPCContext *c) WII_HOT_ATTR("0107");
void f_s_009a7020(PPCContext *c) WII_HOT_ATTR("0108");
void f_k_00009eb0(PPCContext *c) WII_HOT_ATTR("0109");
void f_s_009a2840(PPCContext *c) WII_HOT_ATTR("0110");
void f_g_0007e504(PPCContext *c) WII_HOT_ATTR("0111");
void f_g_0003efe4(PPCContext *c) WII_HOT_ATTR("0112");
void f_gl_0002550c(PPCContext *c) WII_HOT_ATTR("0113");
void f_g_00098234(PPCContext *c) WII_HOT_ATTR("0114");
void f_g_0005e63c(PPCContext *c) WII_HOT_ATTR("0115");
void f_g_000a430c(PPCContext *c) WII_HOT_ATTR("0116");
void f_k_00009ee0(PPCContext *c) WII_HOT_ATTR("0117");
void f_g_00064558(PPCContext *c) WII_HOT_ATTR("0118");
void f_g_0007e3a8(PPCContext *c) WII_HOT_ATTR("0119");
void f_g_000a4150(PPCContext *c) WII_HOT_ATTR("0120");
void f_gl_0002481c(PPCContext *c) WII_HOT_ATTR("0122");
void f_g_0003a11c(PPCContext *c) WII_HOT_ATTR("0124");
void f_g_0004349c(PPCContext *c) WII_HOT_ATTR("0125");
void f_g_00074870(PPCContext *c) WII_HOT_ATTR("0126");
void f_k_00009e80(PPCContext *c) WII_HOT_ATTR("0127");
void f_g_0008f384(PPCContext *c) WII_HOT_ATTR("0128");
void f_gl_00028158(PPCContext *c) WII_HOT_ATTR("0130");
void f_g_0007a86c(PPCContext *c) WII_HOT_ATTR("0131");
void f_g_0007e6a4(PPCContext *c) WII_HOT_ATTR("0132");
void f_g_0006ffbc(PPCContext *c) WII_HOT_ATTR("0133");
void f_g_00040edc(PPCContext *c) WII_HOT_ATTR("0134");
void f_g_000718a4(PPCContext *c) WII_HOT_ATTR("0135");
void f_g_0003f63c(PPCContext *c) WII_HOT_ATTR("0136");
void f_g_000a4430(PPCContext *c) WII_HOT_ATTR("0137");
void f_g_00055fec(PPCContext *c) WII_HOT_ATTR("0138");
void f_g_000566f0(PPCContext *c) WII_HOT_ATTR("0139");
void f_s_009a2ac4(PPCContext *c) WII_HOT_ATTR("0141");
void f_s_009a47e4(PPCContext *c) WII_HOT_ATTR("0142");
void f_s_009a1ab4(PPCContext *c) WII_HOT_ATTR("0143");
void f_g_000accd0(PPCContext *c) WII_HOT_ATTR("0144");
void f_g_0007b888(PPCContext *c) WII_HOT_ATTR("0145");
void f_gl_000201c8(PPCContext *c) WII_HOT_ATTR("0146");
void f_g_00038080(PPCContext *c) WII_HOT_ATTR("0148");
void f_g_00043c38(PPCContext *c) WII_HOT_ATTR("0149");
void f_g_00064148(PPCContext *c) WII_HOT_ATTR("0150");
void f_s_009a7e60(PPCContext *c) WII_HOT_ATTR("0151");
void f_k_00000c00(PPCContext *c) WII_HOT_ATTR("0152");
void f_s_009a3f7c(PPCContext *c) WII_HOT_ATTR("0153");
void f_k_00012618(PPCContext *c) WII_HOT_ATTR("0155");
void f_g_000586f8(PPCContext *c) WII_HOT_ATTR("0156");
void f_g_000a4384(PPCContext *c) WII_HOT_ATTR("0157");
void f_g_000420b0(PPCContext *c) WII_HOT_ATTR("0158");
void f_k_0000ac1c(PPCContext *c) WII_HOT_ATTR("0159");
void f_k_000127e4(PPCContext *c) WII_HOT_ATTR("0160");
void f_s_009a13b0(PPCContext *c) WII_HOT_ATTR("0161");
void f_g_0003f4c4(PPCContext *c) WII_HOT_ATTR("0162");
void f_g_000667dc(PPCContext *c) WII_HOT_ATTR("0163");
void f_g_0005b128(PPCContext *c) WII_HOT_ATTR("0164");
void f_g_00068d7c(PPCContext *c) WII_HOT_ATTR("0166");
void f_g_0003f088(PPCContext *c) WII_HOT_ATTR("0167");
void f_s_009a7784(PPCContext *c) WII_HOT_ATTR("0168");
void f_g_0007fd9c(PPCContext *c) WII_HOT_ATTR("0169");
void f_g_0006657c(PPCContext *c) WII_HOT_ATTR("0170");
void f_g_0003d2b4(PPCContext *c) WII_HOT_ATTR("0171");
void f_k_0000f3d4(PPCContext *c) WII_HOT_ATTR("0172");
void f_g_000446a0(PPCContext *c) WII_HOT_ATTR("0173");
void f_g_00055b94(PPCContext *c) WII_HOT_ATTR("0174");
void f_g_0005c094(PPCContext *c) WII_HOT_ATTR("0175");
void f_g_0005b804(PPCContext *c) WII_HOT_ATTR("0177");
#endif
